// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __VideoStreamService_hh__
#define __VideoStreamService_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_VideoStreamService
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_VideoStreamService
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_VideoStreamService
#endif



#ifndef __BasicDataType_hh_EXTERNAL_GUARD__
#define __BasicDataType_hh_EXTERNAL_GUARD__
#include <BasicDataType.hh>
#endif
#ifndef __ExtendedDataTypes_hh_EXTERNAL_GUARD__
#define __ExtendedDataTypes_hh_EXTERNAL_GUARD__
#include <ExtendedDataTypes.hh>
#endif
#ifndef __InterfaceDataTypes_hh_EXTERNAL_GUARD__
#define __InterfaceDataTypes_hh_EXTERNAL_GUARD__
#include <InterfaceDataTypes.hh>
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





#ifndef __VideoStreamService__
#define __VideoStreamService__

class VideoStreamService;
class _objref_VideoStreamService;
class _impl_VideoStreamService;

typedef _objref_VideoStreamService* VideoStreamService_ptr;
typedef VideoStreamService_ptr VideoStreamServiceRef;

class VideoStreamService_Helper {
public:
  typedef VideoStreamService_ptr _ptr_type;

  static _ptr_type _nil();
  static _CORBA_Boolean is_nil(_ptr_type);
  static void release(_ptr_type);
  static void duplicate(_ptr_type);
  static void marshalObjRef(_ptr_type, cdrStream&);
  static _ptr_type unmarshalObjRef(cdrStream&);
};

typedef _CORBA_ObjRef_Var<_objref_VideoStreamService, VideoStreamService_Helper> VideoStreamService_var;
typedef _CORBA_ObjRef_OUT_arg<_objref_VideoStreamService,VideoStreamService_Helper > VideoStreamService_out;

#endif

// interface VideoStreamService
class VideoStreamService {
public:
  // Declarations for this interface type.
  typedef VideoStreamService_ptr _ptr_type;
  typedef VideoStreamService_var _var_type;

  static _ptr_type _duplicate(_ptr_type);
  static _ptr_type _narrow(::CORBA::Object_ptr);
  static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
  
  static _ptr_type _nil();

  static inline void _marshalObjRef(_ptr_type, cdrStream&);

  static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
    omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
    if (o)
      return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
    else
      return _nil();
  }

  static _core_attr const char* _PD_repoId;

  // Other IDL defined within this scope.
  
};

class _objref_VideoStreamService :
  public virtual ::CORBA::Object,
  public virtual omniObjRef
{
public:
  void capture(::CORBA::Long times);

  inline _objref_VideoStreamService()  { _PR_setobj(0); }  // nil
  _objref_VideoStreamService(omniIOR*, omniIdentity*);

protected:
  virtual ~_objref_VideoStreamService();

  
private:
  virtual void* _ptrToObjRef(const char*);

  _objref_VideoStreamService(const _objref_VideoStreamService&);
  _objref_VideoStreamService& operator = (const _objref_VideoStreamService&);
  // not implemented

  friend class VideoStreamService;
};

class _pof_VideoStreamService : public _OMNI_NS(proxyObjectFactory) {
public:
  inline _pof_VideoStreamService() : _OMNI_NS(proxyObjectFactory)(VideoStreamService::_PD_repoId) {}
  virtual ~_pof_VideoStreamService();

  virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
  virtual _CORBA_Boolean is_a(const char*) const;
};

class _impl_VideoStreamService :
  public virtual omniServant
{
public:
  virtual ~_impl_VideoStreamService();

  virtual void capture(::CORBA::Long times) = 0;
  
public:  // Really protected, workaround for xlC
  virtual _CORBA_Boolean _dispatch(omniCallHandle&);

private:
  virtual void* _ptrToInterface(const char*);
  virtual const char* _mostDerivedRepoId();
  
};


_CORBA_GLOBAL_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_VideoStreamService;



class POA_VideoStreamService :
  public virtual _impl_VideoStreamService,
  public virtual ::PortableServer::ServantBase
{
public:
  virtual ~POA_VideoStreamService();

  inline ::VideoStreamService_ptr _this() {
    return (::VideoStreamService_ptr) _do_this(::VideoStreamService::_PD_repoId);
  }
};







#undef _core_attr
#undef _dyn_attr

void operator<<=(::CORBA::Any& _a, VideoStreamService_ptr _s);
void operator<<=(::CORBA::Any& _a, VideoStreamService_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, VideoStreamService_ptr& _s);



inline void
VideoStreamService::_marshalObjRef(::VideoStreamService_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_VideoStreamService
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_VideoStreamService
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_VideoStreamService
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_VideoStreamService
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_VideoStreamService
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_VideoStreamService
#endif

#endif  // __VideoStreamService_hh__

